package com.yphone.model.nochange;

import java.util.Date;

public class AddressUsed {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_used.address_user_id
     *
     * @mbggenerated
     */
    private Long addressUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_used.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_used.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_used.address_detail
     *
     * @mbggenerated
     */
    private String addressDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_used.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_used.receiver
     *
     * @mbggenerated
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_used.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_used.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_used.address_user_id
     *
     * @return the value of address_used.address_user_id
     *
     * @mbggenerated
     */
    public Long getAddressUserId() {
        return addressUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_used.address_user_id
     *
     * @param addressUserId the value for address_used.address_user_id
     *
     * @mbggenerated
     */
    public void setAddressUserId(Long addressUserId) {
        this.addressUserId = addressUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_used.user_id
     *
     * @return the value of address_used.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_used.user_id
     *
     * @param userId the value for address_used.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_used.area
     *
     * @return the value of address_used.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_used.area
     *
     * @param area the value for address_used.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_used.address_detail
     *
     * @return the value of address_used.address_detail
     *
     * @mbggenerated
     */
    public String getAddressDetail() {
        return addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_used.address_detail
     *
     * @param addressDetail the value for address_used.address_detail
     *
     * @mbggenerated
     */
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail == null ? null : addressDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_used.phone
     *
     * @return the value of address_used.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_used.phone
     *
     * @param phone the value for address_used.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_used.receiver
     *
     * @return the value of address_used.receiver
     *
     * @mbggenerated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_used.receiver
     *
     * @param receiver the value for address_used.receiver
     *
     * @mbggenerated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_used.gmt_create
     *
     * @return the value of address_used.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_used.gmt_create
     *
     * @param gmtCreate the value for address_used.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_used.gmt_modified
     *
     * @return the value of address_used.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_used.gmt_modified
     *
     * @param gmtModified the value for address_used.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_used
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", addressUserId=").append(addressUserId);
        sb.append(", userId=").append(userId);
        sb.append(", area=").append(area);
        sb.append(", addressDetail=").append(addressDetail);
        sb.append(", phone=").append(phone);
        sb.append(", receiver=").append(receiver);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }
}