package com.yphone.model.nochange;

import java.util.Date;

public class AdminInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.admin_id
     *
     * @mbggenerated
     */
    private Long adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.admin_name
     *
     * @mbggenerated
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.is_system_admin
     *
     * @mbggenerated
     */
    private Integer isSystemAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.basic_permission
     *
     * @mbggenerated
     */
    private Integer basicPermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.classify_permission
     *
     * @mbggenerated
     */
    private Integer classifyPermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.user_permission
     *
     * @mbggenerated
     */
    private Integer userPermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.order_permission
     *
     * @mbggenerated
     */
    private Integer orderPermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.admin_id
     *
     * @return the value of admin_info.admin_id
     *
     * @mbggenerated
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.admin_id
     *
     * @param adminId the value for admin_info.admin_id
     *
     * @mbggenerated
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.admin_name
     *
     * @return the value of admin_info.admin_name
     *
     * @mbggenerated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.admin_name
     *
     * @param adminName the value for admin_info.admin_name
     *
     * @mbggenerated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.password
     *
     * @return the value of admin_info.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.password
     *
     * @param password the value for admin_info.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.is_system_admin
     *
     * @return the value of admin_info.is_system_admin
     *
     * @mbggenerated
     */
    public Integer getIsSystemAdmin() {
        return isSystemAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.is_system_admin
     *
     * @param isSystemAdmin the value for admin_info.is_system_admin
     *
     * @mbggenerated
     */
    public void setIsSystemAdmin(Integer isSystemAdmin) {
        this.isSystemAdmin = isSystemAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.basic_permission
     *
     * @return the value of admin_info.basic_permission
     *
     * @mbggenerated
     */
    public Integer getBasicPermission() {
        return basicPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.basic_permission
     *
     * @param basicPermission the value for admin_info.basic_permission
     *
     * @mbggenerated
     */
    public void setBasicPermission(Integer basicPermission) {
        this.basicPermission = basicPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.classify_permission
     *
     * @return the value of admin_info.classify_permission
     *
     * @mbggenerated
     */
    public Integer getClassifyPermission() {
        return classifyPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.classify_permission
     *
     * @param classifyPermission the value for admin_info.classify_permission
     *
     * @mbggenerated
     */
    public void setClassifyPermission(Integer classifyPermission) {
        this.classifyPermission = classifyPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.user_permission
     *
     * @return the value of admin_info.user_permission
     *
     * @mbggenerated
     */
    public Integer getUserPermission() {
        return userPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.user_permission
     *
     * @param userPermission the value for admin_info.user_permission
     *
     * @mbggenerated
     */
    public void setUserPermission(Integer userPermission) {
        this.userPermission = userPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.order_permission
     *
     * @return the value of admin_info.order_permission
     *
     * @mbggenerated
     */
    public Integer getOrderPermission() {
        return orderPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.order_permission
     *
     * @param orderPermission the value for admin_info.order_permission
     *
     * @mbggenerated
     */
    public void setOrderPermission(Integer orderPermission) {
        this.orderPermission = orderPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.gmt_create
     *
     * @return the value of admin_info.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.gmt_create
     *
     * @param gmtCreate the value for admin_info.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.gmt_modified
     *
     * @return the value of admin_info.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.gmt_modified
     *
     * @param gmtModified the value for admin_info.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adminId=").append(adminId);
        sb.append(", adminName=").append(adminName);
        sb.append(", password=").append(password);
        sb.append(", isSystemAdmin=").append(isSystemAdmin);
        sb.append(", basicPermission=").append(basicPermission);
        sb.append(", classifyPermission=").append(classifyPermission);
        sb.append(", userPermission=").append(userPermission);
        sb.append(", orderPermission=").append(orderPermission);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }
}