package com.yphone.model.nochange;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AdminInfoExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    public AdminInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAdminIdIsNull() {
            addCriterion("admin_id is null");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNotNull() {
            addCriterion("admin_id is not null");
            return (Criteria) this;
        }

        public Criteria andAdminIdEqualTo(Long value) {
            addCriterion("admin_id =", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotEqualTo(Long value) {
            addCriterion("admin_id <>", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThan(Long value) {
            addCriterion("admin_id >", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThanOrEqualTo(Long value) {
            addCriterion("admin_id >=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThan(Long value) {
            addCriterion("admin_id <", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThanOrEqualTo(Long value) {
            addCriterion("admin_id <=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdIn(List<Long> values) {
            addCriterion("admin_id in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotIn(List<Long> values) {
            addCriterion("admin_id not in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdBetween(Long value1, Long value2) {
            addCriterion("admin_id between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotBetween(Long value1, Long value2) {
            addCriterion("admin_id not between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminNameIsNull() {
            addCriterion("admin_name is null");
            return (Criteria) this;
        }

        public Criteria andAdminNameIsNotNull() {
            addCriterion("admin_name is not null");
            return (Criteria) this;
        }

        public Criteria andAdminNameEqualTo(String value) {
            addCriterion("admin_name =", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotEqualTo(String value) {
            addCriterion("admin_name <>", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameGreaterThan(String value) {
            addCriterion("admin_name >", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameGreaterThanOrEqualTo(String value) {
            addCriterion("admin_name >=", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameLessThan(String value) {
            addCriterion("admin_name <", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameLessThanOrEqualTo(String value) {
            addCriterion("admin_name <=", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameLike(String value) {
            addCriterion("admin_name like", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotLike(String value) {
            addCriterion("admin_name not like", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameIn(List<String> values) {
            addCriterion("admin_name in", values, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotIn(List<String> values) {
            addCriterion("admin_name not in", values, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameBetween(String value1, String value2) {
            addCriterion("admin_name between", value1, value2, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotBetween(String value1, String value2) {
            addCriterion("admin_name not between", value1, value2, "adminName");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andIsSystemAdminIsNull() {
            addCriterion("is_system_admin is null");
            return (Criteria) this;
        }

        public Criteria andIsSystemAdminIsNotNull() {
            addCriterion("is_system_admin is not null");
            return (Criteria) this;
        }

        public Criteria andIsSystemAdminEqualTo(Integer value) {
            addCriterion("is_system_admin =", value, "isSystemAdmin");
            return (Criteria) this;
        }

        public Criteria andIsSystemAdminNotEqualTo(Integer value) {
            addCriterion("is_system_admin <>", value, "isSystemAdmin");
            return (Criteria) this;
        }

        public Criteria andIsSystemAdminGreaterThan(Integer value) {
            addCriterion("is_system_admin >", value, "isSystemAdmin");
            return (Criteria) this;
        }

        public Criteria andIsSystemAdminGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_system_admin >=", value, "isSystemAdmin");
            return (Criteria) this;
        }

        public Criteria andIsSystemAdminLessThan(Integer value) {
            addCriterion("is_system_admin <", value, "isSystemAdmin");
            return (Criteria) this;
        }

        public Criteria andIsSystemAdminLessThanOrEqualTo(Integer value) {
            addCriterion("is_system_admin <=", value, "isSystemAdmin");
            return (Criteria) this;
        }

        public Criteria andIsSystemAdminIn(List<Integer> values) {
            addCriterion("is_system_admin in", values, "isSystemAdmin");
            return (Criteria) this;
        }

        public Criteria andIsSystemAdminNotIn(List<Integer> values) {
            addCriterion("is_system_admin not in", values, "isSystemAdmin");
            return (Criteria) this;
        }

        public Criteria andIsSystemAdminBetween(Integer value1, Integer value2) {
            addCriterion("is_system_admin between", value1, value2, "isSystemAdmin");
            return (Criteria) this;
        }

        public Criteria andIsSystemAdminNotBetween(Integer value1, Integer value2) {
            addCriterion("is_system_admin not between", value1, value2, "isSystemAdmin");
            return (Criteria) this;
        }

        public Criteria andBasicPermissionIsNull() {
            addCriterion("basic_permission is null");
            return (Criteria) this;
        }

        public Criteria andBasicPermissionIsNotNull() {
            addCriterion("basic_permission is not null");
            return (Criteria) this;
        }

        public Criteria andBasicPermissionEqualTo(Integer value) {
            addCriterion("basic_permission =", value, "basicPermission");
            return (Criteria) this;
        }

        public Criteria andBasicPermissionNotEqualTo(Integer value) {
            addCriterion("basic_permission <>", value, "basicPermission");
            return (Criteria) this;
        }

        public Criteria andBasicPermissionGreaterThan(Integer value) {
            addCriterion("basic_permission >", value, "basicPermission");
            return (Criteria) this;
        }

        public Criteria andBasicPermissionGreaterThanOrEqualTo(Integer value) {
            addCriterion("basic_permission >=", value, "basicPermission");
            return (Criteria) this;
        }

        public Criteria andBasicPermissionLessThan(Integer value) {
            addCriterion("basic_permission <", value, "basicPermission");
            return (Criteria) this;
        }

        public Criteria andBasicPermissionLessThanOrEqualTo(Integer value) {
            addCriterion("basic_permission <=", value, "basicPermission");
            return (Criteria) this;
        }

        public Criteria andBasicPermissionIn(List<Integer> values) {
            addCriterion("basic_permission in", values, "basicPermission");
            return (Criteria) this;
        }

        public Criteria andBasicPermissionNotIn(List<Integer> values) {
            addCriterion("basic_permission not in", values, "basicPermission");
            return (Criteria) this;
        }

        public Criteria andBasicPermissionBetween(Integer value1, Integer value2) {
            addCriterion("basic_permission between", value1, value2, "basicPermission");
            return (Criteria) this;
        }

        public Criteria andBasicPermissionNotBetween(Integer value1, Integer value2) {
            addCriterion("basic_permission not between", value1, value2, "basicPermission");
            return (Criteria) this;
        }

        public Criteria andClassifyPermissionIsNull() {
            addCriterion("classify_permission is null");
            return (Criteria) this;
        }

        public Criteria andClassifyPermissionIsNotNull() {
            addCriterion("classify_permission is not null");
            return (Criteria) this;
        }

        public Criteria andClassifyPermissionEqualTo(Integer value) {
            addCriterion("classify_permission =", value, "classifyPermission");
            return (Criteria) this;
        }

        public Criteria andClassifyPermissionNotEqualTo(Integer value) {
            addCriterion("classify_permission <>", value, "classifyPermission");
            return (Criteria) this;
        }

        public Criteria andClassifyPermissionGreaterThan(Integer value) {
            addCriterion("classify_permission >", value, "classifyPermission");
            return (Criteria) this;
        }

        public Criteria andClassifyPermissionGreaterThanOrEqualTo(Integer value) {
            addCriterion("classify_permission >=", value, "classifyPermission");
            return (Criteria) this;
        }

        public Criteria andClassifyPermissionLessThan(Integer value) {
            addCriterion("classify_permission <", value, "classifyPermission");
            return (Criteria) this;
        }

        public Criteria andClassifyPermissionLessThanOrEqualTo(Integer value) {
            addCriterion("classify_permission <=", value, "classifyPermission");
            return (Criteria) this;
        }

        public Criteria andClassifyPermissionIn(List<Integer> values) {
            addCriterion("classify_permission in", values, "classifyPermission");
            return (Criteria) this;
        }

        public Criteria andClassifyPermissionNotIn(List<Integer> values) {
            addCriterion("classify_permission not in", values, "classifyPermission");
            return (Criteria) this;
        }

        public Criteria andClassifyPermissionBetween(Integer value1, Integer value2) {
            addCriterion("classify_permission between", value1, value2, "classifyPermission");
            return (Criteria) this;
        }

        public Criteria andClassifyPermissionNotBetween(Integer value1, Integer value2) {
            addCriterion("classify_permission not between", value1, value2, "classifyPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionIsNull() {
            addCriterion("user_permission is null");
            return (Criteria) this;
        }

        public Criteria andUserPermissionIsNotNull() {
            addCriterion("user_permission is not null");
            return (Criteria) this;
        }

        public Criteria andUserPermissionEqualTo(Integer value) {
            addCriterion("user_permission =", value, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionNotEqualTo(Integer value) {
            addCriterion("user_permission <>", value, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionGreaterThan(Integer value) {
            addCriterion("user_permission >", value, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_permission >=", value, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionLessThan(Integer value) {
            addCriterion("user_permission <", value, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionLessThanOrEqualTo(Integer value) {
            addCriterion("user_permission <=", value, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionIn(List<Integer> values) {
            addCriterion("user_permission in", values, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionNotIn(List<Integer> values) {
            addCriterion("user_permission not in", values, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionBetween(Integer value1, Integer value2) {
            addCriterion("user_permission between", value1, value2, "userPermission");
            return (Criteria) this;
        }

        public Criteria andUserPermissionNotBetween(Integer value1, Integer value2) {
            addCriterion("user_permission not between", value1, value2, "userPermission");
            return (Criteria) this;
        }

        public Criteria andOrderPermissionIsNull() {
            addCriterion("order_permission is null");
            return (Criteria) this;
        }

        public Criteria andOrderPermissionIsNotNull() {
            addCriterion("order_permission is not null");
            return (Criteria) this;
        }

        public Criteria andOrderPermissionEqualTo(Integer value) {
            addCriterion("order_permission =", value, "orderPermission");
            return (Criteria) this;
        }

        public Criteria andOrderPermissionNotEqualTo(Integer value) {
            addCriterion("order_permission <>", value, "orderPermission");
            return (Criteria) this;
        }

        public Criteria andOrderPermissionGreaterThan(Integer value) {
            addCriterion("order_permission >", value, "orderPermission");
            return (Criteria) this;
        }

        public Criteria andOrderPermissionGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_permission >=", value, "orderPermission");
            return (Criteria) this;
        }

        public Criteria andOrderPermissionLessThan(Integer value) {
            addCriterion("order_permission <", value, "orderPermission");
            return (Criteria) this;
        }

        public Criteria andOrderPermissionLessThanOrEqualTo(Integer value) {
            addCriterion("order_permission <=", value, "orderPermission");
            return (Criteria) this;
        }

        public Criteria andOrderPermissionIn(List<Integer> values) {
            addCriterion("order_permission in", values, "orderPermission");
            return (Criteria) this;
        }

        public Criteria andOrderPermissionNotIn(List<Integer> values) {
            addCriterion("order_permission not in", values, "orderPermission");
            return (Criteria) this;
        }

        public Criteria andOrderPermissionBetween(Integer value1, Integer value2) {
            addCriterion("order_permission between", value1, value2, "orderPermission");
            return (Criteria) this;
        }

        public Criteria andOrderPermissionNotBetween(Integer value1, Integer value2) {
            addCriterion("order_permission not between", value1, value2, "orderPermission");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}