package com.yphone.model.nochange;

import java.util.Date;

public class District {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.district_id
     *
     * @mbggenerated
     */
    private Short districtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.parent_id
     *
     * @mbggenerated
     */
    private Short parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.initial
     *
     * @mbggenerated
     */
    private String initial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.initials
     *
     * @mbggenerated
     */
    private String initials;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.pinyin
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.extra
     *
     * @mbggenerated
     */
    private String extra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.suffix
     *
     * @mbggenerated
     */
    private String suffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.area_code
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.order
     *
     * @mbggenerated
     */
    private Short order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.district_id
     *
     * @return the value of district.district_id
     *
     * @mbggenerated
     */
    public Short getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.district_id
     *
     * @param districtId the value for district.district_id
     *
     * @mbggenerated
     */
    public void setDistrictId(Short districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.name
     *
     * @return the value of district.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.name
     *
     * @param name the value for district.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.parent_id
     *
     * @return the value of district.parent_id
     *
     * @mbggenerated
     */
    public Short getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.parent_id
     *
     * @param parentId the value for district.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Short parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.initial
     *
     * @return the value of district.initial
     *
     * @mbggenerated
     */
    public String getInitial() {
        return initial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.initial
     *
     * @param initial the value for district.initial
     *
     * @mbggenerated
     */
    public void setInitial(String initial) {
        this.initial = initial == null ? null : initial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.initials
     *
     * @return the value of district.initials
     *
     * @mbggenerated
     */
    public String getInitials() {
        return initials;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.initials
     *
     * @param initials the value for district.initials
     *
     * @mbggenerated
     */
    public void setInitials(String initials) {
        this.initials = initials == null ? null : initials.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.pinyin
     *
     * @return the value of district.pinyin
     *
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.pinyin
     *
     * @param pinyin the value for district.pinyin
     *
     * @mbggenerated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.extra
     *
     * @return the value of district.extra
     *
     * @mbggenerated
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.extra
     *
     * @param extra the value for district.extra
     *
     * @mbggenerated
     */
    public void setExtra(String extra) {
        this.extra = extra == null ? null : extra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.suffix
     *
     * @return the value of district.suffix
     *
     * @mbggenerated
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.suffix
     *
     * @param suffix the value for district.suffix
     *
     * @mbggenerated
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix == null ? null : suffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.code
     *
     * @return the value of district.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.code
     *
     * @param code the value for district.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.area_code
     *
     * @return the value of district.area_code
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.area_code
     *
     * @param areaCode the value for district.area_code
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.order
     *
     * @return the value of district.order
     *
     * @mbggenerated
     */
    public Short getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.order
     *
     * @param order the value for district.order
     *
     * @mbggenerated
     */
    public void setOrder(Short order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.gmt_create
     *
     * @return the value of district.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.gmt_create
     *
     * @param gmtCreate the value for district.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.gmt_modified
     *
     * @return the value of district.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.gmt_modified
     *
     * @param gmtModified the value for district.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", districtId=").append(districtId);
        sb.append(", name=").append(name);
        sb.append(", parentId=").append(parentId);
        sb.append(", initial=").append(initial);
        sb.append(", initials=").append(initials);
        sb.append(", pinyin=").append(pinyin);
        sb.append(", extra=").append(extra);
        sb.append(", suffix=").append(suffix);
        sb.append(", code=").append(code);
        sb.append(", areaCode=").append(areaCode);
        sb.append(", order=").append(order);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }
}