package com.yphone.model.nochange;

import java.util.Date;

public class OrderGenerator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_generator.order_generator_id
     *
     * @mbggenerated
     */
    private Long orderGeneratorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_generator.phone_last4
     *
     * @mbggenerated
     */
    private String phoneLast4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_generator.date_num
     *
     * @mbggenerated
     */
    private String dateNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_generator.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_generator.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_generator.order_generator_id
     *
     * @return the value of order_generator.order_generator_id
     *
     * @mbggenerated
     */
    public Long getOrderGeneratorId() {
        return orderGeneratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_generator.order_generator_id
     *
     * @param orderGeneratorId the value for order_generator.order_generator_id
     *
     * @mbggenerated
     */
    public void setOrderGeneratorId(Long orderGeneratorId) {
        this.orderGeneratorId = orderGeneratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_generator.phone_last4
     *
     * @return the value of order_generator.phone_last4
     *
     * @mbggenerated
     */
    public String getPhoneLast4() {
        return phoneLast4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_generator.phone_last4
     *
     * @param phoneLast4 the value for order_generator.phone_last4
     *
     * @mbggenerated
     */
    public void setPhoneLast4(String phoneLast4) {
        this.phoneLast4 = phoneLast4 == null ? null : phoneLast4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_generator.date_num
     *
     * @return the value of order_generator.date_num
     *
     * @mbggenerated
     */
    public String getDateNum() {
        return dateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_generator.date_num
     *
     * @param dateNum the value for order_generator.date_num
     *
     * @mbggenerated
     */
    public void setDateNum(String dateNum) {
        this.dateNum = dateNum == null ? null : dateNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_generator.gmt_create
     *
     * @return the value of order_generator.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_generator.gmt_create
     *
     * @param gmtCreate the value for order_generator.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_generator.gmt_modified
     *
     * @return the value of order_generator.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_generator.gmt_modified
     *
     * @param gmtModified the value for order_generator.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_generator
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderGeneratorId=").append(orderGeneratorId);
        sb.append(", phoneLast4=").append(phoneLast4);
        sb.append(", dateNum=").append(dateNum);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }
}