package com.yphone.model.nochange;

import java.math.BigDecimal;
import java.util.Date;

public class PhoneInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.phone_id
     *
     * @mbggenerated
     */
    private Long phoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.color
     *
     * @mbggenerated
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.capacity
     *
     * @mbggenerated
     */
    private Short capacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.RAM
     *
     * @mbggenerated
     */
    private Integer ram;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.size
     *
     * @mbggenerated
     */
    private BigDecimal size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.pixels
     *
     * @mbggenerated
     */
    private Short pixels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.sales
     *
     * @mbggenerated
     */
    private Integer sales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.url1
     *
     * @mbggenerated
     */
    private String url1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.url2
     *
     * @mbggenerated
     */
    private String url2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_info.url3
     *
     * @mbggenerated
     */
    private String url3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.phone_id
     *
     * @return the value of phone_info.phone_id
     *
     * @mbggenerated
     */
    public Long getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.phone_id
     *
     * @param phoneId the value for phone_info.phone_id
     *
     * @mbggenerated
     */
    public void setPhoneId(Long phoneId) {
        this.phoneId = phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.name
     *
     * @return the value of phone_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.name
     *
     * @param name the value for phone_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.price
     *
     * @return the value of phone_info.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.price
     *
     * @param price the value for phone_info.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.type
     *
     * @return the value of phone_info.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.type
     *
     * @param type the value for phone_info.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.color
     *
     * @return the value of phone_info.color
     *
     * @mbggenerated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.color
     *
     * @param color the value for phone_info.color
     *
     * @mbggenerated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.capacity
     *
     * @return the value of phone_info.capacity
     *
     * @mbggenerated
     */
    public Short getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.capacity
     *
     * @param capacity the value for phone_info.capacity
     *
     * @mbggenerated
     */
    public void setCapacity(Short capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.RAM
     *
     * @return the value of phone_info.RAM
     *
     * @mbggenerated
     */
    public Integer getRam() {
        return ram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.RAM
     *
     * @param ram the value for phone_info.RAM
     *
     * @mbggenerated
     */
    public void setRam(Integer ram) {
        this.ram = ram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.size
     *
     * @return the value of phone_info.size
     *
     * @mbggenerated
     */
    public BigDecimal getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.size
     *
     * @param size the value for phone_info.size
     *
     * @mbggenerated
     */
    public void setSize(BigDecimal size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.weight
     *
     * @return the value of phone_info.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.weight
     *
     * @param weight the value for phone_info.weight
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.pixels
     *
     * @return the value of phone_info.pixels
     *
     * @mbggenerated
     */
    public Short getPixels() {
        return pixels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.pixels
     *
     * @param pixels the value for phone_info.pixels
     *
     * @mbggenerated
     */
    public void setPixels(Short pixels) {
        this.pixels = pixels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.gmt_create
     *
     * @return the value of phone_info.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.gmt_create
     *
     * @param gmtCreate the value for phone_info.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.gmt_modified
     *
     * @return the value of phone_info.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.gmt_modified
     *
     * @param gmtModified the value for phone_info.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.description
     *
     * @return the value of phone_info.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.description
     *
     * @param description the value for phone_info.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.num
     *
     * @return the value of phone_info.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.num
     *
     * @param num the value for phone_info.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.sales
     *
     * @return the value of phone_info.sales
     *
     * @mbggenerated
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.sales
     *
     * @param sales the value for phone_info.sales
     *
     * @mbggenerated
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.url
     *
     * @return the value of phone_info.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.url
     *
     * @param url the value for phone_info.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.url1
     *
     * @return the value of phone_info.url1
     *
     * @mbggenerated
     */
    public String getUrl1() {
        return url1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.url1
     *
     * @param url1 the value for phone_info.url1
     *
     * @mbggenerated
     */
    public void setUrl1(String url1) {
        this.url1 = url1 == null ? null : url1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.url2
     *
     * @return the value of phone_info.url2
     *
     * @mbggenerated
     */
    public String getUrl2() {
        return url2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.url2
     *
     * @param url2 the value for phone_info.url2
     *
     * @mbggenerated
     */
    public void setUrl2(String url2) {
        this.url2 = url2 == null ? null : url2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_info.url3
     *
     * @return the value of phone_info.url3
     *
     * @mbggenerated
     */
    public String getUrl3() {
        return url3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_info.url3
     *
     * @param url3 the value for phone_info.url3
     *
     * @mbggenerated
     */
    public void setUrl3(String url3) {
        this.url3 = url3 == null ? null : url3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", phoneId=").append(phoneId);
        sb.append(", name=").append(name);
        sb.append(", price=").append(price);
        sb.append(", type=").append(type);
        sb.append(", color=").append(color);
        sb.append(", capacity=").append(capacity);
        sb.append(", ram=").append(ram);
        sb.append(", size=").append(size);
        sb.append(", weight=").append(weight);
        sb.append(", pixels=").append(pixels);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", description=").append(description);
        sb.append(", num=").append(num);
        sb.append(", sales=").append(sales);
        sb.append(", url=").append(url);
        sb.append(", url1=").append(url1);
        sb.append(", url2=").append(url2);
        sb.append(", url3=").append(url3);
        sb.append("]");
        return sb.toString();
    }
}