package com.yphone.model.nochange;

import java.util.Date;

public class ShoppingCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_card.shopping_card_id
     *
     * @mbggenerated
     */
    private Long shoppingCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_card.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_card.phone_id
     *
     * @mbggenerated
     */
    private Long phoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_card.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_card.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_card.shopping_card_id
     *
     * @return the value of shopping_card.shopping_card_id
     *
     * @mbggenerated
     */
    public Long getShoppingCardId() {
        return shoppingCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_card.shopping_card_id
     *
     * @param shoppingCardId the value for shopping_card.shopping_card_id
     *
     * @mbggenerated
     */
    public void setShoppingCardId(Long shoppingCardId) {
        this.shoppingCardId = shoppingCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_card.user_id
     *
     * @return the value of shopping_card.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_card.user_id
     *
     * @param userId the value for shopping_card.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_card.phone_id
     *
     * @return the value of shopping_card.phone_id
     *
     * @mbggenerated
     */
    public Long getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_card.phone_id
     *
     * @param phoneId the value for shopping_card.phone_id
     *
     * @mbggenerated
     */
    public void setPhoneId(Long phoneId) {
        this.phoneId = phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_card.gmt_create
     *
     * @return the value of shopping_card.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_card.gmt_create
     *
     * @param gmtCreate the value for shopping_card.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_card.gmt_modified
     *
     * @return the value of shopping_card.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_card.gmt_modified
     *
     * @param gmtModified the value for shopping_card.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_card
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shoppingCardId=").append(shoppingCardId);
        sb.append(", userId=").append(userId);
        sb.append(", phoneId=").append(phoneId);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }
}