package com.yphone.mappers.nochange;

import com.yphone.model.nochange.PhoneInfo;
import com.yphone.model.nochange.PhoneInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGPhoneInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_info
     *
     * @mbggenerated
     */
    int countByExample(PhoneInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_info
     *
     * @mbggenerated
     */
    int deleteByExample(PhoneInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long phoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_info
     *
     * @mbggenerated
     */
    int insert(PhoneInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_info
     *
     * @mbggenerated
     */
    int insertSelective(PhoneInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_info
     *
     * @mbggenerated
     */
    List<PhoneInfo> selectByExample(PhoneInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_info
     *
     * @mbggenerated
     */
    PhoneInfo selectByPrimaryKey(Long phoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PhoneInfo record, @Param("example") PhoneInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PhoneInfo record, @Param("example") PhoneInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PhoneInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PhoneInfo record);
}