package com.yphone.mappers.nochange;

import com.yphone.model.nochange.ShoppingCard;
import com.yphone.model.nochange.ShoppingCardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGShoppingCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_card
     *
     * @mbggenerated
     */
    int countByExample(ShoppingCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_card
     *
     * @mbggenerated
     */
    int deleteByExample(ShoppingCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_card
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long shoppingCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_card
     *
     * @mbggenerated
     */
    int insert(ShoppingCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_card
     *
     * @mbggenerated
     */
    int insertSelective(ShoppingCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_card
     *
     * @mbggenerated
     */
    List<ShoppingCard> selectByExample(ShoppingCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_card
     *
     * @mbggenerated
     */
    ShoppingCard selectByPrimaryKey(Long shoppingCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_card
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ShoppingCard record, @Param("example") ShoppingCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_card
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ShoppingCard record, @Param("example") ShoppingCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_card
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShoppingCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_card
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShoppingCard record);
}