package util.mode;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.ID
     *
     * @mbggenerated Sat Jul 14 11:21:20 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.name
     *
     * @mbggenerated Sat Jul 14 11:21:20 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.teacher
     *
     * @mbggenerated Sat Jul 14 11:21:20 CST 2018
     */
    private String teacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.details
     *
     * @mbggenerated Sat Jul 14 11:21:20 CST 2018
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated Sat Jul 14 11:21:20 CST 2018
     */
    public Course(String id, String name, String teacher, String details) {
        this.id = id;
        this.name = name;
        this.teacher = teacher;
        this.details = details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated Sat Jul 14 11:21:20 CST 2018
     */
    public Course() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.ID
     *
     * @return the value of courses.ID
     *
     * @mbggenerated Sat Jul 14 11:21:20 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.ID
     *
     * @param id the value for courses.ID
     *
     * @mbggenerated Sat Jul 14 11:21:20 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.name
     *
     * @return the value of courses.name
     *
     * @mbggenerated Sat Jul 14 11:21:20 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.name
     *
     * @param name the value for courses.name
     *
     * @mbggenerated Sat Jul 14 11:21:20 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.teacher
     *
     * @return the value of courses.teacher
     *
     * @mbggenerated Sat Jul 14 11:21:20 CST 2018
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.teacher
     *
     * @param teacher the value for courses.teacher
     *
     * @mbggenerated Sat Jul 14 11:21:20 CST 2018
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.details
     *
     * @return the value of courses.details
     *
     * @mbggenerated Sat Jul 14 11:21:20 CST 2018
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.details
     *
     * @param details the value for courses.details
     *
     * @mbggenerated Sat Jul 14 11:21:20 CST 2018
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}